AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instance with preconfigured TeamCity CI/CD pipeline.

Parameters:
  EnvironmentName:
    Description: Template name
    Type: String
    Default: EC2TeamCity
  MyKeyPair:
    Description: List of available keys in eu-west-1 region
    Type: AWS::EC2::KeyPair::KeyName
  MyIpAddress: 
    Type: String
    Description: My IP address
    Default: 0.0.0.0/0

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-09e2d756e7d78558d
      InstanceType: t3.small
      KeyName: !Ref MyKeyPair
      Monitoring: false
      SecurityGroups: 
        - !Ref InstanceSG
      Tags: 
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum update
          # Install Java 8 Corretto from AWS 
          amazon-linux-extras enable corretto8
          yum install -y java-1.8.0-amazon-corretto-devel
          # Install TeamCity
          wget https://download.jetbrains.com/teamcity/TeamCity-2022.04.3.tar.gz
          tar xfz TeamCity-2022.04.3.tar.gz
          cd TeamCity/bin/
          ./runAll.sh start
          EOF

  InstanceEBS:
    Type: AWS::EC2::Volume
    Properties: 
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
      Encrypted: false
      MultiAttachEnabled: false
      Size: 20
      Tags: 
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
      VolumeType: gp2

  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and https to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8111
          ToPort: 8111
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIpAddress

Outputs:
  EC2PublicDNS:
    Description: Public DNS of EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
  
  Ec2PublicIP:
    Description: Public IP of EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
